{
 "title": "Babylon Validator & Finality Provider Dashboard",
 "description": "This is a personal monitoring dashboard for validator or finality provider or both of them",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cvms_block_height{chain=\"babylon\"},chain_id)"
    }
   },
   {
    "name": "table_chain_id",
    "query": {
     "query": "label_values(cvms_block_height{chain_id=\"$chain_id\"},table_chain_id)"
    }
   },
   { "name": "blocks", "label": "monitoring blocks", "query": "10" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is a playground for developers and beta release testing for CVMS.\n</p>\n<p>\n  <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Github Link Here!\n  </a> \n  <a href=\"https://github.com/cosmostation/cvms/blob/release/docs/setup.md\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Setup Guide Here!!\n  </a> \n</p>"
   }
  },
  {
   "title": "Indexer Sync Delay",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - cvms_root_index_pointer_timestamp{chain_id='$chain_id'}",
     "legendFormat": "{{package}}"
    }
   ]
  },
  {
   "title": "Finality Provider Uptime Trend",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(1 - cvms_babylon_finality_provider_missed_votes_counter{chain_id='$chain_id'} / on (chain_id) group_left cvms_babylon_finality_provider_signed_votes_window, 0.001) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finality Provider Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM babylon_finality_provider_${table_chain_id}\n)\nSELECT\n  bfp.height,\n  bfp.status,\n  fpi.moniker AS moniker,\n  fpi.operator_address as address,\n  fpi.btc_pk as btc_pk\nFROM\n  babylon_finality_provider_${table_chain_id} bfp\nJOIN\n  meta.finality_provider_info fpi\n  ON bfp.finality_provider_pk_id = fpi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON bfp.height BETWEEN (mh.highest_height - ${blocks}) AND mh.highest_height\nORDER by\n  bfp.height ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Consensus Uptime Trend",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((1 - sum(cvms_uptime_missed_blocks_counter{chain_id='$chain_id'}) without (instance, job, package, validator_consensus_address, validator_operator_address, proposer_address) / on (chain_id) group_left cvms_uptime_signed_blocks_window) * 100, 0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM voteindexer_${table_chain_id}\n)\nSELECT\n  vidx.height,\n  vidx.status,\n  vi.moniker AS moniker\nFROM\n  voteindexer_${table_chain_id} vidx\nJOIN\n  meta.validator_info vi\n  ON vidx.validator_hex_address_id = vi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON vidx.height BETWEEN (mh.highest_height - ${blocks}) AND mh.highest_height\nORDER by\n  vidx.height ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Checkpoint BLS Signing",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cvms_babylon_checkpoint_bls_signature_missed_total{chain_id='$chain_id'}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Checkpoint BLS Vote Status",
   "type": "nline-plotlyjs-panel",
   "description": "Extension Vote means ABCI++(2.0) feature.",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH epoch AS (\n  SELECT MAX(epoch) as max_epoch FROM babylon_checkpoint_${table_chain_id}\n)\n select\n  idx.height,\n  idx.status,\n  vi.moniker AS moniker,\n  idx.epoch\nFROM\n  babylon_checkpoint_${table_chain_id} idx\nJOIN\n  meta.validator_info vi\n  ON idx.validator_hex_address_id = vi.id\nJOIN\n  epoch\n  ON idx.epoch BETWEEN (epoch.max_epoch - ${blocks}) AND epoch.max_epoch\nORDER by\n  idx.height DESC\n"
    }
   ]
  }
 ]
}