{
 "title": "Babylon Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cvms_block_timestamp{chain=\"babylon\"},chain_id)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values(cvms_block_timestamp{table_chain_id=\"$chain_id\"},chain)"
    }
   },
   {
    "name": "table_chain_id",
    "query": {
     "query": "label_values(cvms_block_height{chain_id=\"$chain_id\"},table_chain_id)"
    }
   },
   { "name": "blocks", "label": "monitor_blocks", "query": "30" },
   { "name": "epochs", "label": "monitor epochs", "query": "50" },
   { "name": "lightclient_blocks", "label": "lightclient blocks", "query": "100" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is a playground for developers and beta release testing for CVMS.\n</p>\n<p>\n  <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Github Link Here!\n  </a> \n  <a href=\"https://github.com/cosmostation/cvms/blob/release/docs/setup.md\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Setup Guide Here!!\n  </a> \n</p>"
   }
  },
  {
   "title": "Indexer Sync Delay",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - cvms_root_index_pointer_timestamp{chain_id='$chain_id'}",
     "legendFormat": "{{package}}"
    }
   ]
  },
  { "title": "Block Data Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Block Gas Usage %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cvms_block_data_analytics_block_gas_used{chain_id='$chain_id'} / scalar(cvms_block_data_analytics_block_max_gas)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Bytes Usage %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cvms_block_data_analytics_block_txs_bytes{chain_id='$chain_id'} / scalar(cvms_block_data_analytics_block_max_bytes)) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Blocks Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "select \n\tbda.height, \n\tbda.total_gas_used,\n\tbda.total_gas_wanted,\n\tbda.total_txs_bytes,\n\tbda.success_txs_count,\n\tbda.failed_txs_count\nfrom block_data_analytics_${table_chain_id} bda \nORDER BY height desc\nlimit 10;"
    }
   ]
  },
  { "title": "Babylon Third Party Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "BTC LightClient Reporter Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM babylon_btc_lightclient_${table_chain_id}\n)\nSELECT\n  bbl.height, -- height, header_count, btc_headers.\n  bbl.is_roll_back::INTEGER,\n  vi.operator_address as address,\n  bbl.roll_forward_count,\n  bbl.roll_back_count,\n  bbl.btc_height\nFROM\n  babylon_btc_lightclient_${table_chain_id} bbl\nJOIN\n  meta.vigilante_info vi\n  ON bbl.reporter_id = vi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON bbl.height BETWEEN (mh.highest_height - ${lightclient_blocks}) AND mh.highest_height\nORDER BY height asc"
    }
   ]
  },
  {
   "title": "Covenant Signing State",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "WITH latest_delegations AS (\n    SELECT * \n    FROM public.babylon_btc_delegation_${table_chain_id}\n    ORDER BY height DESC\n    LIMIT 100\n)\nSELECT \n    ld.chain_info_id,\n    ld.height AS delegation_height,\n    ld.btc_staking_tx_hash,\n    cci.moniker,\n    COALESCE(bcs.height, -1) AS signature_height,  \n    COALESCE(bcs.covenant_btc_pk_id, cci.id) AS covenant_btc_pk_id,\n    COALESCE(cci.covenant_btc_pk, 'N/A') AS covenant_btc_pk,\n    CASE \n        WHEN bcs.btc_staking_tx_hash IS NOT NULL AND cci.id IS NOT NULL THEN TRUE\n        ELSE FALSE\n    END AS status\nFROM latest_delegations ld\nCROSS JOIN meta.covenant_committee_info cci \nLEFT JOIN public.babylon_covenant_signature_${table_chain_id} bcs \n    ON ld.btc_staking_tx_hash = bcs.btc_staking_tx_hash\n    and cci.moniker = cci.moniker\n    AND ld.chain_info_id = bcs.chain_info_id\n    AND cci.id = bcs.covenant_btc_pk_id\nWHERE ld.chain_info_id = cci.chain_info_id\nORDER BY ld.height DESC, cci.id;"
    }
   ]
  },
  { "title": "Finality Provider Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Finality Provider Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 34, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM babylon_finality_provider_${table_chain_id}\n)\nSELECT\n  bfp.height,\n  bfp.status,\n  fpi.moniker AS moniker,\n  fpi.operator_address as address,\n  fpi.btc_pk as btc_pk\nFROM\n  babylon_finality_provider_${table_chain_id} bfp\nJOIN\n  meta.finality_provider_info fpi\n  ON bfp.finality_provider_pk_id = fpi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON bfp.height BETWEEN (mh.highest_height - ${blocks}) AND mh.highest_height\nORDER by\n  bfp.height ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Finality Provider Uptime Trend",
   "type": "timeseries",
   "gridPos": { "h": 34, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(1 - cvms_babylon_finality_provider_missed_votes_counter{chain_id='$chain_id'} / on (chain_id) group_left cvms_babylon_finality_provider_signed_votes_window, 0.001) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator Signing Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Consensus Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 40, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": ";\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM voteindexer_${table_chain_id}\n)\nSELECT\n  vidx.height,\n  vidx.status,\n  vi.moniker AS moniker\nFROM\n  voteindexer_${table_chain_id} vidx\nJOIN\n  meta.validator_info vi\n  ON vidx.validator_hex_address_id = vi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON vidx.height BETWEEN (mh.highest_height - ${blocks}) AND mh.highest_height\nORDER by\n  vidx.height ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Checkpoint BLS Vote Status",
   "type": "nline-plotlyjs-panel",
   "description": "Extension Vote means ABCI++(2.0) feature.",
   "gridPos": { "h": 40, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "rawSql": "\n\n select\n  idx.height, \n  idx.status,\n  vi.moniker AS moniker,\n  idx.epoch\nFROM\n  babylon_checkpoint_bbn_1 idx\nJOIN\n  meta.validator_info vi\n  ON idx.validator_hex_address_id = vi.id\nWHERE\n  idx.epoch >= (\n    SELECT MAX(epoch) - (${epochs} - 1)\n    FROM babylon_checkpoint_${table_chain_id}\n  )\nORDER BY\n  idx.epoch desc"
    }
   ]
  }
 ]
}