{
 "title": "Babylon FP Health Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "chain-id",
    "query": {
     "query": "label_values(cvms_block_timestamp{chain=\"babylon\"},chain_id)"
    }
   },
   {
    "name": "table_chain_id",
    "label": "table_chain_id",
    "query": {
     "query": "label_values(cvms_block_timestamp{chain_id=\"$chain_id\"},table_chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Indexer Sync Delay",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - cvms_root_index_pointer_timestamp{chain_id='$chain_id'}",
     "legendFormat": "{{package}}"
    }
   ]
  },
  {
   "title": "Finality Provider Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 38, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM babylon_finality_provider_${table_chain_id}\n)\nSELECT\n  bfp.height,\n  bfp.status,\n  fpi.moniker AS moniker,\n  fpi.operator_address as address,\n  fpi.btc_pk as btc_pk\nFROM\n  babylon_finality_provider_${table_chain_id} bfp\nJOIN\n  meta.finality_provider_info fpi\n  ON bfp.finality_provider_pk_id = fpi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON bfp.height BETWEEN (mh.highest_height - 50) AND mh.highest_height\nORDER by\n  bfp.height ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "cvms_babylon_finality_provider_last_finalized_block_height{chain_id='$chain_id'}",
     "legendFormat": "block height"
    }
   ]
  },
  {
   "title": "Missing FP Votes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "cvms_babylon_finality_provider_last_finalized_block_missing_votes_count{chain_id='$chain_id'}",
     "legendFormat": "missing votes"
    }
   ]
  },
  {
   "title": "missing VP / total VP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "cvms_babylon_finality_provider_last_finalized_block_missing_vp{chain_id='$chain_id'} / (cvms_babylon_finality_provider_last_finalized_block_finalized_vp+cvms_babylon_finality_provider_last_finalized_block_missing_vp)",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cvms_babylon_finality_provider_voting_power{chain_id='$chain_id'} / scalar(sum(cvms_babylon_finality_provider_voting_power)) > 0",
     "legendFormat": "{{moniker}}"
    }
   ]
  }
 ]
}