{
 "title": "Hippocrat Testnet Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cvms_block_timestamp{chain=\"hippocrat\"},chain_id)"
    }
   },
   {
    "name": "table_chain_id",
    "query": {
     "query": "label_values(cvms_block_timestamp{chain_id=\"$chain_id\"},table_chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is part of the beta launch, with the open-source repository coming soon.\n</p>\n<p>\n  <a href=\"https://public-cosmos-vms.cosmostation.io/d/be37h6ce99dz4e/network-duty-dashboard?from=now-30m\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 Validator Duty Overview Click Here\n  </a> \n  <a href=\"https://public-cosmos-vms.cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 Validator Consensus Overview Click Here\n  </a> \n</p>"
   }
  },
  {
   "title": "Validator Golden Timer",
   "type": "table",
   "description": "The golden time means you should recover back up in consensus in specific duration. if not, your validator node will be jailed by onchain parameter ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ceil(cvms_uptime_signed_blocks_window * (1 - cvms_uptime_min_signed_per_window)) - on (chain_id) group_right () cvms_uptime_missed_blocks_counter{table_chain_id='${chain_id}'}) without (proposer_address, validator_consensus_address, validator_operator_address, instance, job, package, service)\n* on (chain_id) group_left () (min by (chain_id) (3600 / delta(cvms_block_height[1h])))"
    }
   ]
  },
  {
   "title": "Recent Consensus Vote",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "\nSELECT \n    vi.moniker, \n    COUNT(CASE WHEN status = 1 THEN 1 END) AS missed,\n    COUNT(CASE WHEN status = 2 THEN 1 END) AS commited,\n    COUNT(CASE WHEN status = 3 THEN 1 END) AS proposed\nFROM voteindexer_${table_chain_id} vidx\nJOIN meta.validator_info vi ON vidx.validator_hex_address_id = vi.id\nWHERE height > ((SELECT MAX(height) FROM voteindexer_${table_chain_id}) - 100)\nGROUP BY vi.moniker\norder by missed desc\n"
    }
   ]
  },
  { "title": "CometBFT Consensus Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Validator Consensus Vote Status (${chain}/${chain_id})",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": ";  -- Order in ascending order for the last 100 blocks\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM voteindexer_${table_chain_id}\n)\nSELECT\n  vidx.height,\n  vidx.status,\n  vi.moniker AS moniker\nFROM\n  voteindexer_${table_chain_id} vidx\nJOIN\n  meta.validator_info vi\n  ON vidx.validator_hex_address_id = vi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON vidx.height BETWEEN (mh.highest_height - 100) AND mh.highest_height\nORDER by\n  vidx.height ASC\n  \n  "
    }
   ]
  }
 ]
}